### PR TITLE
fix: use /start/ link instead of /p/ in /SSOViews/linking

### LINKED ISSUE #138: Linking page still uses /p/ URLs, causes redirect URI error
**Describe the bug**
The linking page (/SSOViews/linking) still uses the older /p/ format for its URLs. When linking to authentik in this way, there is an error that "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)".

By manually editing the URL to use /start/, the link works as expected.

**To Reproduce**

1. Go to the page "/SSOViews/linking" on the Jellyfin instance.
2. Click on '+' for an authentik provider.
3. See error page: "The request fails due to a missing, invalid, or mismatching redirection URI (redirect_uri)".

**Expected behavior**
The user is able to login with the authentik provider

**Configuration**
https://pastebin.com/eKkXj0KY

**Versions (please complete the following information):**

- OS: Linux
- Browser: Chrome 116
- Jellyfin Version: 10.8.10
- Plugin Version: 3.5.2.0

### PR DESCRIPTION
**Pull request by imnatgreen**
Fixes #138

### CODE REVIEW

**Comment by 9p4** [comment]
This would then break the old configurations as well. How can we have it pick the right URL?

**Comment by strazto** [comment]
> This would then break the old configurations as well. How can we have it pick the right URL?

Easiest way is probably duplicate the link button with a hidden button that uses the `p` version, and add a checkbox that says "legacy redirect url (use if having problems)" that hides one version or shows the other.

**However**, the current version of the plugin **only** documents the new form, so new users will likely be very confounded by parts of the app falling back to wholly undocumented APIs.

I think it's worth transitioning here.

A more complicated and slightly more end-user friendly approach would be to allow admins to configure an option for which version to use by default, but IMO the amount of effort of adding this functionality for backwards compatibility isn't worth it.

It's probably also worth adding something to the docs / some FAQ that outlines the soft-deprecation and describes a migration path.

The migration is quite simple, but it's not that obvious what changed and when.

**Comment by adamzvolanek** [comment]
> This would then break the old configurations as well. How can we have it pick the right URL?

As a current user who tried to migrated from version 3.4.0.0 to the latest and update my Authentik and JellyFin redirects, its not been a pretty transition and the SSO Plugin has locked me out of my own JellyFin instance. My Authentik still redirects on the old path, but for some reason, even after disabling the plugin in the `system.xml`, I am out of options and having to re-create my JellyFin instance.

**Comment by 9p4** [comment]
Would you mind testing out the latest commit? I've implemented something: https://github.com/9p4/jellyfin-plugin-sso/commit/9321c25f2028101cee19f4bf90083aecb60bdba5

**Pull request closed without merging**
