### PR TITLE
Improve UX on config page

### LINKED ISSUE #2: Admin page
Tracking issue for the admin page

### PR DESCRIPTION
**Pull request by matthewstrasiotto**
Resolves #2

Done:
- [x] Revisit help texts, particularly 
   - [x] https://github.com/9p4/jellyfin-plugin-sso/pull/18#discussion_r857147909 (Enable Authorization)
   - [x] Help text for all un-json'd fields
   - [x] Uh 
- [x] Stylesheet improvements, particularly for:
  - [x] Role map list should be clearly delineated, paddings and colours of the nested checklists need to be improved to clearly mark their connection to the input field.
- [x] ~Input validation~
  - [x] ~Optional json fields should send empty placeholder~  https://github.com/9p4/jellyfin-plugin-sso/issues/23#issuecomment-1114064728
     - **JSON Fields have all been removed** 
- [x] Improve UX for configuring complex properties
   (JSON is not acceptable long term)
   - [x] **1a** Folder selection should resemble https://github.com/jellyfin/jellyfin-plugin-ldapauth
     https://github.com/9p4/jellyfin-plugin-sso/pull/18#discussion_r857148061
     image
   - [x] Role Selection 
     - https://github.com/9p4/jellyfin-plugin-sso/pull/18#discussion_r857148156
     - (Applies to both admin role & standard role)
     - won't work like folder selection, as listing roles requires authenticating with SSO provider to enumerate roles
     Options:
       - [x] **2a** Give role lists as multiline text input, split on newline (Relatively simple, decent UX)
       - **2b** ~Implement some kind of list-append dialog, similar to builtin library / folder management (More complex, better (?) UX)~
         image
- [x] Role -> Folder Mapping
   - https://github.com/9p4/jellyfin-plugin-sso/pull/18#discussion_r857148344
   - I envisage this will look like a combination of **2b** + **1a**, where selecting the "+" (add) button creates a dialog with a text input, for the role name, and a set of checkboxes for each library that role should have access to.

### CODE REVIEW

**Comment by matthewstrasiotto** [comment]
@9p4 ready for review

**Comment by matthewstrasiotto** [comment]
I request a release be made to the manifest upon this PR's merge

**Comment by 9p4** [comment]
Sure, I'll put out a new release (maybe not 4.0 though)

**Comment by 9p4** [comment]
Looks good, but I would prefer the multi-line textareas to be below the slug instead of inline.

Furthermore, I think there needs to be a tiny bit more info for "Roles" and "Admin Roles" and whether or not the roles are separated by newlines.

**Comment by matthewstrasiotto** [comment]
> Looks good, but I would prefer the multi-line textareas to be below the slug instead of inline.

I'm not sure what you mean by that, this is what they look like to me

image

Unless you mean the folder role mapping inputs

image

> Furthermore, I think there needs to be a tiny bit more info for "Roles" and "Admin Roles" and whether or not the roles are separated by newlines.

good point

**Comment by matthewstrasiotto** [comment]
Role mappings:

image

Help strings:

image

**Comment by matthewstrasiotto** [comment]
if it's ready to merge, I'd rather squash https://github.com/9p4/jellyfin-plugin-sso/commit/6e198efc02b94429cbc7dcfc0b925ca0f82affeb into https://github.com/9p4/jellyfin-plugin-sso/pull/27/commits/46682139c415e807bb0d42489a8d11d3633ae6a8

**Comment by 9p4** [comment]
This is what I see on Firefox

**Comment by matthewstrasiotto** [comment]
> This is what I see on Firefox
> 
> 

Ew! Looks terrible!

I'll try it on Firefox, I copied the textarea styling over from Jellyfin's, since for some reason they don't expose the textarea stylesheet to plugin pages, and maybe there was something missing

**Comment by matthewstrasiotto** [comment]
I don't know how to reproduce your problem on firefox, for me it looks like this:

image

**Comment by matthewstrasiotto** [comment]
It looks fine on all my browsers, it kind of looks like the entire stylesheet isn't being loaded 

https://github.com/9p4/jellyfin-plugin-sso/pull/27/files#diff-dbce8897198b98e490eac0f35c3bce167a71104bd110d7df7b6c6ae2b12b6cbdR340-R345

Is this code running okay?

I've introduced the stylesheet as another embedded asset, is something going wrong there?

**Comment by 9p4** [comment]
Seems like the stylesheet isn't loading when Jellyfin is served under a subdirectory.

**Comment by 9p4** [comment]
Yep that's the issue

**Comment by 9p4** [comment]
Should be `/jellyfin/web/configurationpage...`

Seems like a bug in JF.

**Comment by 9p4** [comment]
Scratch that, it's a bug in the JS

```
  addTextAreaStyle: (view) => {
    var style = document.createElement("link");
    style.rel = "stylesheet";
    style.href = "/web/configurationpage?name=SSO-Auth.css";
    view.appendChild(style);
  },
```

**Comment by 9p4** [comment]
Alright it seems to be all fixed now.

**Comment by 9p4** [comment]
Before I merge, there are a few more issues. First, the Folder-Role mapping doesn't have the proper role nor folders.



Maybe for the default providers, add a hint for what a suitable entry would be. Maybe `Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider`?

**Comment by 9p4** [comment]
Just checked and it doesn't seem like the per-provider allowed folders isn't working either (POSTing an empty array, doesn't populate)

**Comment by 9p4** [comment]
Alright, those issues should all be fixed now. Let me know your thoughts before I merge.

**Comment by matthewstrasiotto** [comment]
I'll have a look, but if it's all good from your end, I'm happy. 
Just squash merge it if you can, please :)

**Comment by matthewstrasiotto** [comment]
LGTM

**Pull request merged**
